version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."

  build:
    commands:
      - echo "Starting build phase"
      - cd src
      - echo "Running SAM build..."
      - sam build --template-file ../saml.yaml

  post_build:
    commands:
      - echo "Starting post-build phase"
      - sam package --output-template-file ../samout.yaml --s3-bucket pipeline-creation-bucket --region ap-south-1 --template-file ../saml.yaml
      - echo "Packaging complete"

artifacts:
  files:
    - samout.yaml
