version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Install AWS CLI or other dependencies here if needed.

  pre_build:
    commands:
      - echo "Preparing the environment..."

  build:
    commands:
      - echo "Building the serverless application..."
      - sam build --template-file saml.yaml

  post_build:
    commands:
      - echo "Packaging the serverless application..."
      - sam package --output-template-file samout.yaml --s3-bucket pipeline-creation-bucket --region ap-south-1 --template-file saml.yaml
      - echo "Checking if samout.yaml exists..."
      - ls -l samout.yaml
      - echo "Deploying the serverless application..."
      - sam deploy --template-file samout.yaml --stack-name my-stack --capabilities CAPABILITY_IAM --debug

artifacts:
  files:
    - samout.yaml
  discard-paths: yes
