version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo Pre-build phase
      - echo Preparing for build

  build:
    commands:
      - echo Building the SAM application
      - sam build --template-file src/saml.yaml --output-template-file .aws-sam/build/template.yaml

  post_build:
    commands:
      - echo Packaging the serverless application...
      - sam package --output-template-file .aws-sam/output/samout.yaml --s3-bucket pipeline-creation-bucket --region ap-south-1
      - echo Deploying the serverless application...
      - sam deploy --template-file .aws-sam/output/samout.yaml --stack-name poc-backup --capabilities CAPABILITY_IAM

artifacts:
  files:
    - .aws-sam/output/samout.yaml
