version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the serverless application..."
      - sam build --template-file saml.yaml  # Use the correct path to saml.yaml
  post_build:
    commands:
      - echo "Packaging the serverless application..."
      - sam package --output-template-file samout.yaml --s3-bucket pipeline-creation-bucket --region ap-south-1 --template-file saml.yaml  # Correct SAM packaging command

artifacts:
  files:
    - samout.yaml  # Ensure you are outputting the correct artifact
