version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase: No dependencies to install"

  build:
    commands:
      - echo "Building the serverless application"
      - sam build --template-file saml.yaml  # Builds the application

  post_build:
    commands:
      - echo "Packaging the serverless application..."
      - sam package --output-template-file samout.yaml --s3-bucket pipeline-creation-bucket --region ap-south-1 --template-file saml.yaml
      - echo "Packaging complete"

artifacts:
  files:
    - samout.yaml  # Ensure samout.yaml is included as an artifact
