version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing SAM CLI..."
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template-file saml.yaml
  build:
    commands:
      - echo "Building the serverless application..."
      - sam build --template-file saml.yaml
  post_build:
    commands:
      - echo "Packaging the serverless application..."
      - sam package --output-template-file samout.yaml
      - echo "Listing files in the current directory..."
      - ls -al

artifacts:
  files:
    - samout.yaml
