version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install aws-sam-cli  # Install SAM CLI if not already installed

  pre_build:
    commands:
      - echo Preparing for build...

  build:
    commands:
      - echo Building SAM application...
      - sam build --template-file src/saml.yaml  # Build the application using the template from src/saml.yaml
      - sam package --output-template-file samout.yaml --s3-bucket pipeline-creation-bucket --region $AWS_DEFAULT_REGION  # Package the SAM app

  post_build:
    commands:
      - echo Packaging the serverless application...
      - sam deploy --template-file samout.yaml --stack-name poc-backup --capabilities CAPABILITY_IAM  # Deploy the app to the CloudFormation stack

artifacts:
  files:
    - samout.yaml  # Ensure the output template file is included as an artifact
