version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install aws-sam-cli  # Install AWS SAM CLI
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template-file saml.yaml  # Validate the SAM template
  build:
    commands:
      - echo "Building the serverless application..."
      - sam build --template-file saml.yaml  # Build the SAM application
  post_build:
    commands:
      - echo "Packaging the serverless application..."
      - sam package \
          --output-template-file samout.yaml \
          --s3-bucket pipeline-creation-bucket \
          --region ap-south-1  # Package the SAM application
      - echo "Listing files in the current directory after packaging..."
      - ls -al  # List the files to confirm samout.yaml is created

artifacts:
  files:
    - samout.yaml  # Upload the packaged CloudFormation template as an artifact
