version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the serverless application..."
      - sam build --template-file saml.yaml
  post_build:
    commands:
      - echo "Packaging the serverless application..."
      - sam package --output-template-file samout.yaml --s3-bucket pipeline-creation-bucket --region ap-south-1 --template-file saml.yaml
  deploy:
    commands:
      - echo "Deploying the packaged application..."
      - sam deploy --template-file samout.yaml --stack-name my-stack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - samout.yaml
  discard-paths: yes
