AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple serverless application.

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/  # Correct path to the src folder
      Handler: app.lambda_handler  # Lambda function entry point
      Runtime: python3.10
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
